frase = input('Digite algo: ')
print(f'É numerico ? {frase.isnumeric()}')
print(f'É maiusculo ? {frase.isupper()}')
print(f'É minusculo ? {frase.islower()}')
print(f'É numerico e alfabetico ? {frase.isalnum()}')
